language: node_js

node_js:
  - "8"
  - "10"

addons:
  postgresql: "9.4"
  apt:
    packages:
      - postgresql-server-dev-9.4

env:
  TEST_DATABASE_URL: postgres://localhost:5432/travis
  PGVERSION: 9.4

cache: yarn

install:
  - yarn

before_script:
  - psql -c "ALTER USER travis WITH PASSWORD 'travis';"
  - sudo service postgresql restart

script:
  - scripts/test

matrix:
  include:
    - addons:
        apt:
          packages:
            - postgresql-10
            - postgresql-client-10
            - postgresql-server-dev-10
        postgresql: 10
      env:
        - PGPORT=5433
        - TEST_DATABASE_URL=postgres://travis:travis@localhost:5433/travis
        - PGVERSION=10
      sudo: false
      dist: trusty
