name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install dep
      run: npm install && npm install graphile-build graphile-build-pg
    - name: Build
      run: npm run build
