name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install peer installer
      run: npm install --save-dev --ignore-scripts install-peers
    - name: Install dep
      run: npm install
    - name: Build
      run: npm run build
